export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/modules";
export * from "@/pages/dashboard/team";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/wellnessHub";
export * from "@/pages/dashboard/ownTracking";
export * from "@/pages/dashboard/teams";
export * from "@/pages/dashboard/404";
export * from "@/pages/dashboard/resumenes";